version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "dev-main"
    labels:
      - patch
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "dev-main"
    labels:
      - dependencies
      - docker
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "dev-main"
    labels:
      - dependencies
      - python
    groups:
      python-production:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      python-development:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
