version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "dev-main"
    labels:
      - patch
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "dev-main"
    labels:
      - dependencies
      - docker
    groups:
      docker:
        patterns:
          - "*"
