"""add_favourite_field_to_chat_table

Revision ID: 2ce9e79b185c
Revises: f092ac68cceb
Create Date: 2025-10-02 13:32:14.059231

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ce9e79b185c"
down_revision: Union[str, None] = "f092ac68cceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("chat", sa.Column("favourite", sa.Boolean(), server_default="false", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("chat", "favourite")

    # ### end Alembic commands ###
