"""add public_link and share_code to chat table

Revision ID: 887fa86569b8
Revises: 22b1a192325b
Create Date: 2025-11-17 23:39:52.790735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "887fa86569b8"
down_revision: Union[str, None] = "22b1a192325b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("share", sa.Boolean(), nullable=False, server_default=sa.text("false")))

    op.add_column("chat", sa.Column("share_code", sa.CHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "share")
    op.drop_column("chat", "share_code")
    # ### end Alembic commands ###
