"""Add mesage_id key to GovUkSearchQuery

Revision ID: b94d5504e4be
Revises: e2db35a465f5
Create Date: 2025-06-26 18:00:28.347666

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b94d5504e4be"
down_revision: Union[str, None] = "e2db35a465f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gov_uk_search_query", sa.Column("message_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "gov_uk_search_query", "message", ["message_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gov_uk_search_query", "message_id")
    # ### end Alembic commands ###
