"""Add summary fields to message table

Revision ID: f092ac68cceb
Revises: 7bcf445bcd0e
Create Date: 2025-08-06 08:13:58.419711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f092ac68cceb"
down_revision: Union[str, None] = "7bcf445bcd0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("message", sa.Column("summary_llm_response_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "summary_llm_response_id")
    op.drop_column("message", "summary")
    # ### end Alembic commands ###
