from app.config import GCS_DATA_API_URL

URL_SMART_TARGETS_HEALTHCHECK = f"{GCS_DATA_API_URL}/healthcheck"
URL_SMART_TARGETS_METRICS = f"{GCS_DATA_API_URL}/v1/metrics"
URL_SMART_TARGETS_FILTERS = f"{URL_SMART_TARGETS_METRICS}/{{metric_uuid}}/filters"
URL_SMART_TARGETS_MEASUREMENTS = f"{URL_SMART_TARGETS_METRICS}/{{metric_uuid}}/measurements"
URL_SMART_TARGETS_SUMMARY = f"{URL_SMART_TARGETS_METRICS}/{{metric_uuid}}/summary"
