name: Check for fixup! commits

on:
  pull_request:

jobs:
  check-for-fixup-commits:
    name: Check for fixup! commits
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for fixup! commits
        shell: bash
        run: |
          if [[ $(git log --pretty=oneline --grep=^fixup! ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}) ]]; then
            echo "fixup! commits found. Squash these before merging."
            exit 1
          fi
