name: Check pull request label

on:
  pull_request:
    branches:
      - dev-main
    types: [opened, reopened, synchronize, labeled]

jobs:
  check_pull_request_label:
    name: Check pull request label
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check for the PR label
        uses: zwaldowski/match-label-action@v5
        with:
          allowed: major,minor,patch,bugfix,chore,documentation
