name: Security and Lint Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: |
          bandit -r app/ tests/ --severity high
          if [ $? -ne 0 ]; then
            echo "::warning::Security issues detected! Check the logs above."
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .

      - name: Secret Scanning with Trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
